#بسم الله الرحمن الرحيم
#la ilaha illa Allah mohammed rassoul Allah

bismi_allah:
	gcc -o bin/bismi_allah  `pkg-config --cflags --libs sdl2` bismi_allah.c

bismi_allah_windows:
	x86_64-w64-mingw32-gcc -o bin/bismi_allah  `x86_64-w64-mingw32-pkg-config --cflags --libs sdl2` bismi_allah.c
